import 'package:flutter/material.dart';
import '../../models/pool_model.dart';
import '../../models/shared_expense_model.dart';
import '../../models/user_model.dart';
import '../../services/firestore_service.dart';
import '../../theme/app_colors.dart';
import 'package:firebase_auth/firebase_auth.dart';

class AddSharedExpenseSheet extends StatefulWidget {
  final PoolModel pool;

  const AddSharedExpenseSheet({super.key, required this.pool});

  @override
  State<AddSharedExpenseSheet> createState() => _AddSharedExpenseSheetState();
}

class _AddSharedExpenseSheetState extends State<AddSharedExpenseSheet> {
  final _descController = TextEditingController();
  final _amountController = TextEditingController();

  String _paidByUid = '';
  String _splitType = 'Equal'; // Equal, Exact, Percentage

  // uid -> value (either exact amount or percentage)
  Map<String, double> _splitValues = {};
  
  // To show member names
  Map<String, String> _memberNames = {};
  bool _isLoadingMembers = true;
  bool _isSaving = false;

  @override
  void initState() {
    super.initState();
    _paidByUid = FirebaseAuth.instance.currentUser?.uid ?? '';
    
    // Initialize splits to 0
    for (String uid in widget.pool.members) {
      _splitValues[uid] = 0.0;
    }

    _loadMemberNames();
  }

  Future<void> _loadMemberNames() async {
    for (String uid in widget.pool.members) {
      UserModel? user = await FirestoreService().getUser(uid);
      if (mounted) {
        setState(() {
          _memberNames[uid] = user != null && user.displayName.isNotEmpty 
              ? user.displayName 
              : 'User ($uid)';
        });
      }
    }
    if (mounted) setState(() => _isLoadingMembers = false);
  }

  @override
  void dispose() {
    _descController.dispose();
    _amountController.dispose();
    super.dispose();
  }

  Future<void> _saveExpense() async {
    if (_descController.text.trim().isEmpty || _amountController.text.trim().isEmpty) {
      return;
    }

    double totalAmount = double.tryParse(_amountController.text) ?? 0.0;
    if (totalAmount <= 0) return;

    setState(() => _isSaving = true);

    Map<String, double> finalSplits = {};

    try {
      if (_splitType == 'Equal') {
        double splitAmount = totalAmount / widget.pool.members.length;
        for (String uid in widget.pool.members) {
          finalSplits[uid] = splitAmount;
        }
      } else if (_splitType == 'Exact') {
        double sum = 0;
        _splitValues.forEach((key, value) => sum += value);
        if ((sum - totalAmount).abs() > 0.1) { // allow 10 cents floating error max
          throw Exception('Exact amounts must sum up to the total amount (₹$totalAmount). Current sum: ₹$sum');
        }
        finalSplits = Map.from(_splitValues);
      } else if (_splitType == 'Percentage') {
        double sum = 0;
        _splitValues.forEach((key, value) => sum += value);
        if ((sum - 100).abs() > 0.1) {
          throw Exception('Percentages must sum exactly to 100%. Current sum: $sum%');
        }
        for (String uid in widget.pool.members) {
          finalSplits[uid] = totalAmount * (_splitValues[uid]! / 100.0);
        }
      }

      final expense = SharedExpenseModel(
        id: '', // Generated by Firestore
        poolId: widget.pool.id,
        description: _descController.text.trim(),
        amount: totalAmount,
        paidBy: _paidByUid,
        date: DateTime.now(),
        splits: finalSplits,
      );

      await FirestoreService().addSharedExpense(expense);
      if (mounted) Navigator.pop(context);
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(e.toString().replaceAll('Exception: ', ''))),
        );
      }
    } finally {
      if (mounted) setState(() => _isSaving = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoadingMembers) {
      return Container(
        height: 300,
        decoration: const BoxDecoration(
          color: AppColors.pureWhite,
          borderRadius: BorderRadius.only(topLeft: Radius.circular(28), topRight: Radius.circular(28)),
        ),
        child: const Center(child: CircularProgressIndicator()),
      );
    }

    return Container(
      decoration: const BoxDecoration(
        color: AppColors.backgroundWhite,
        borderRadius: BorderRadius.only(topLeft: Radius.circular(28), topRight: Radius.circular(28)),
      ),
      padding: EdgeInsets.fromLTRB(24, 12, 24, MediaQuery.of(context).viewInsets.bottom + 24),
      child: SingleChildScrollView(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Center(
              child: Container(
                width: 40,
                height: 4,
                margin: const EdgeInsets.only(bottom: 20),
                decoration: BoxDecoration(
                  color: AppColors.borderLight,
                  borderRadius: BorderRadius.circular(2),
                ),
              ),
            ),
            const Text(
              'Add Shared Expense',
              style: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.bold,
                color: AppColors.darkBlue,
              ),
            ),
            const SizedBox(height: 20),

            // Description
            TextField(
              controller: _descController,
              decoration: const InputDecoration(
                hintText: 'What was it for? (e.g. Dinner)',
                prefixIcon: Icon(Icons.receipt_long_rounded),
              ),
            ),
            const SizedBox(height: 16),

            // Amount
            TextField(
              controller: _amountController,
              keyboardType: const TextInputType.numberWithOptions(decimal: true),
              decoration: const InputDecoration(
                hintText: 'Total Amount (₹)',
                prefixIcon: Icon(Icons.currency_rupee_rounded),
              ),
            ),
            const SizedBox(height: 20),

            // Paid By
            const Text('Paid by', style: TextStyle(fontWeight: FontWeight.w600, color: AppColors.darkBlue)),
            const SizedBox(height: 8),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 16),
              decoration: BoxDecoration(
                color: AppColors.pureWhite,
                borderRadius: BorderRadius.circular(16),
                border: Border.all(color: AppColors.borderLight),
              ),
              child: DropdownButtonHideUnderline(
                child: DropdownButton<String>(
                  value: _paidByUid,
                  isExpanded: true,
                  items: widget.pool.members.map((uid) {
                    return DropdownMenuItem(
                      value: uid,
                      child: Text(_memberNames[uid] ?? 'Unknown'),
                    );
                  }).toList(),
                  onChanged: (val) {
                    if (val != null) setState(() => _paidByUid = val);
                  },
                ),
              ),
            ),
            const SizedBox(height: 20),

            // Split Type
            const Text('How to split?', style: TextStyle(fontWeight: FontWeight.w600, color: AppColors.darkBlue)),
            const SizedBox(height: 8),
            SegmentedButton<String>(
              segments: const [
                ButtonSegment(value: 'Equal', label: Text('Equally', style: TextStyle(fontSize: 12))),
                ButtonSegment(value: 'Exact', label: Text('Exact Amt', style: TextStyle(fontSize: 12))),
                ButtonSegment(value: 'Percentage', label: Text('Percentage', style: TextStyle(fontSize: 12))),
              ],
              selected: {_splitType},
              onSelectionChanged: (val) => setState(() => _splitType = val.first),
              style: SegmentedButton.styleFrom(
                selectedBackgroundColor: AppColors.primaryBlue.withAlpha(20),
                selectedForegroundColor: AppColors.primaryBlue,
              ),
            ),
            const SizedBox(height: 16),

            // Manual Split Inputs (if not Equal)
            if (_splitType != 'Equal')
              ...widget.pool.members.map((uid) {
                return Padding(
                  padding: const EdgeInsets.only(bottom: 12),
                  child: Row(
                    children: [
                      Expanded(flex: 2, child: Text(_memberNames[uid] ?? 'Unknown')),
                      Expanded(
                        flex: 3,
                        child: TextField(
                          keyboardType: const TextInputType.numberWithOptions(decimal: true),
                          decoration: InputDecoration(
                            hintText: '0.00',
                            prefixIcon: _splitType == 'Exact' 
                                ? const Icon(Icons.currency_rupee_rounded, size: 16)
                                : null,
                            suffixIcon: _splitType == 'Percentage'
                                ? const Padding(padding: EdgeInsets.all(14), child: Text('%'))
                                : null,
                            isDense: true,
                          ),
                          onChanged: (val) {
                            _splitValues[uid] = double.tryParse(val) ?? 0.0;
                          },
                        ),
                      ),
                    ],
                  ),
                );
              }),

            const SizedBox(height: 24),
            ElevatedButton(
              onPressed: _isSaving ? null : _saveExpense,
              style: ElevatedButton.styleFrom(
                padding: const EdgeInsets.symmetric(vertical: 16),
                backgroundColor: AppColors.primaryBlue,
                foregroundColor: AppColors.pureWhite,
              ),
              child: _isSaving
                  ? const SizedBox(height: 20, width: 20, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
                  : const Text('Save Shared Expense', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
            ),
          ],
        ),
      ),
    );
  }
}
